foo = 3

# The problems with this file's output (in simpler.json) are:
#
# A. the foo symbol has no "defn" property; it should have defn="0-7"
# B. the foo symbol should have no docstring; it has "Generated by CoffeeScript..."
# C. there are 2 refs to foo in span 0-3; should only be 1 (with def=true)
#
# The generate code is:
#
#  // Generated by CoffeeScript 2.0.0-beta8
#  var foo;
#  foo = 3;
#
# The source map (labeled with "# mN" for reference below) is:
#
#  [ { generated: { line: 1, column: 0 }, # m1
#     original: { line: 1, column: 0 },
#     source: 'testdata/simpler.coffee',
#     name: null },
#   { generated: { line: 2, column: 4 },  # m2
#     original: { line: 1, column: 0 },
#     source: 'testdata/simpler.coffee',
#     name: 'foo' },
#   { generated: { line: 2, column: 8 },  # m3
#     original: { line: 1, column: 0 },
#     source: 'testdata/simpler.coffee',
#     name: null },
#   { generated: { line: 3, column: 0 },  # m4
#     original: { line: 1, column: 0 },
#     source: 'testdata/simpler.coffee',
#     name: 'foo' },
#   { generated: { line: 3, column: 3 },  # m5
#     original: { line: 1, column: 0 },
#     source: 'testdata/simpler.coffee',
#     name: null },
#   { generated: { line: 3, column: 6 },  # m6
#     original: { line: 1, column: 6 },
#     source: 'testdata/simpler.coffee',
#     name: null },
#   { generated: { line: 3, column: 7 },  # m7
#     original: { line: 1, column: 0 },
#     source: 'testdata/simpler.coffee',
#     name: null } ]
