foo = 3

# The problems with this file's output (in simpler.json) are:
#
# * the foo symbol has no "defn" property; it should have defn="0-7"
# * the foo symbol should have no docstring; it has "Generated by CoffeeScript..."
# * there are 2 refs to foo in span 0-3; should only be 1 (with def=true)